micronaut:
  application:
    name: budgetbot
  server:
    port: 7070
  http:
    client:
      read-timeout: 10s
      connect-timeout: 5s

datasources:
  default:
    url: "jdbc:h2:file:./data/database;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'"
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    schema-generate: NONE
    dialect: H2

monobank:
  base-url: https://api.monobank.ua
  webhook-public-url: ${MONOBANK_WEBHOOK_PUBLIC_URL:}
  webhook-secret: ${MONOBANK_WEBHOOK_SECRET:}

endpoints:
  health:
    enabled: true
    sensitive: false
