micronaut:
  application:
    name: budgetbot
  server:
    port: 7070
  http:
    client:
      read-timeout: 10s
      connect-timeout: 5s

datasources:
  default:
    url: jdbc:h2:file:./data/database
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.H2Dialect

monobank:
  base-url: "https://api.monobank.ua"

endpoints:
  health:
    enabled: true
    sensitive: false
